name: 0ad
adopt-info: 0ad-unix-build
summary: Real-time strategy game of ancient warfare
description: |
 0 A.D. (pronounced “zero-ey-dee”) is a free, open-source, historical
 Real Time Strategy (RTS) game currently under development by Wildfire Games,
 a global group of volunteer game developers.
 As the leader of an ancient civilization, you must gather the resources
 you need to raise a military force and dominate your enemies.
 .
 “0 A.D.” is a time period that never actually existed: In the usual calendar,
 one goes from 1 B.C. to 1 A.D. and skips zero. This reflects the historical
 fiction in the game: Who would have won if all the factions were pitted
 against each other when each of them was at its prime?
 .
 We intend to portray some of the major civilizations over the millennium of
 500 B.C. to 500 A.D. (Hence the midpoint, zero.) That is an ambitious prospect,
 so in the first edition of 0 A.D. we focus on the last five centuries B.C.
 Perhaps in future expansion packs, more civilizations will be added,
 along with additional gameplay features.
 .
 We put a strong emphasis on historical accuracy while developing 0 A.D.
 We plan all our units and all our buildings based on reconstructions of how
 the units and the buildings might have looked like in the ancient world.
 We even name them in the original languages, such as Greek and Latin.
 But it’s worth remembering that any game should be fun to play, so,
 in many cases, we preferred playability over historical accuracy.
license: GPL-2.0+
confinement: strict
base: core24

apps:
  0ad:
    command-chain:
      - bin/gpu-2404-wrapper
    command: play0ad.launcher
    desktop: 0ad.desktop
    common-id: com.play0ad.zeroad
    plugs:
      - audio-playback
      - desktop
      - home
      - network
      - network-bind
      - opengl
      - removable-media
      - screen-inhibit-control
      - x11
  atlas:
    command-chain:
      - bin/gpu-2404-wrapper
    command: play0ad.launcher -editor
    plugs:
      - audio-playback
      - desktop
      - home
      - opengl
      - removable-media
      - x11

plugs:
  gpu-2404:
    interface: content
    target: $SNAP/gpu-2404
    default-provider: mesa-2404
  icon-themes:
    interface: content
    target: $SNAP/data-dir/icons
    default-provider: gtk-common-themes

layout:
  /usr/share/X11/XErrorDB:
    symlink: $SNAP/gpu-2404/X11/XErrorDB

parts:
  rustc:
    plugin: rust
    rust-channel: 1.76.0
    source: .
    override-build: |
      rustup component remove clippy rust-docs
      cargo install --locked cbindgen
    override-prime: 'true'
  0ad-unix-build:
    after: [rustc]
    plugin: nil
    source: https://jenkins.wildfiregames.com/job/0ad-bundles/lastSuccessfulBuild/artifact/0ad-0.28.0dev-unix-build.tar.xz
    source-checksum: sha1/de569885476d83bed08288324b3ecd4b27b0cf74
    build-packages:
      - binutils
      - cmake
      - findutils
      - g++
      - grep
      - libboost-dev
      - libboost-filesystem-dev
      - libcurl4-gnutls-dev
      - libenet-dev
      - libfmt-dev
      - libfreetype-dev
      - libgloox-dev
      - libminiupnpc-dev
      - libogg-dev
      - libopenal-dev
      - libpng-dev
      - libsdl2-dev
      - libsodium-dev
      - libvorbis-dev
      - libwxgtk3.2-dev
      - libxml2-dev
      - llvm
      - m4
      - make
      - patch
      - pkg-config
      - python3
      - sed
      - uuid-dev
      - zlib1g-dev
    override-pull: |
      craftctl default
      craftctl set version="$(sed 's/L\"release-\(.*\),.*/\1/' build/build_version/build_version.txt)-dev"
    override-build: |
      for patch in fcollada-move premake-clean spidermonkey-no-debug spidermonkey-strip spidermonkey-unpack-minimal spidermonkey-thin-archive
      do
        patch -d . -p1 < "${CRAFT_PROJECT_DIR}/patches/${patch}.patch"
      done
      env SHELL=/bin/sh libraries/build-source-libs.sh -j${CRAFT_PARALLEL_BUILD_COUNT}
      rm -rf libraries/source/spidermonkey/lib/*
      build/workspaces/update-workspaces.sh -j${CRAFT_PARALLEL_BUILD_COUNT}
      make -j${CRAFT_PARALLEL_BUILD_COUNT} config=release -C build/workspaces/gcc
      rm -rf build/workspaces/gcc
      P=binaries/system
      rm -rf ${P}/*.a ${P}/test
      find ${P} -type f -executable -exec strip --strip-all {} +
      mkdir -p ${CRAFT_PART_INSTALL}/${P}
      cp ${P}/libnvcore.so ${P}/libnvimage.so ${P}/libnvmath.so ${P}/libnvtt.so ${CRAFT_PART_INSTALL}/${P}/
      cp ${P}/pyrogenesis ${P}/ActorEditor ${P}/libAtlasUI.so ${P}/libCollada.so ${P}/libmozjs*-release.so ${P}/readme.txt ${CRAFT_PART_INSTALL}/${P}/
      P=binaries/data/l10n
      mkdir -p ${CRAFT_PART_INSTALL}/${P}
      cp ${P}/*.po ${CRAFT_PART_INSTALL}/${P}/
      cp build/resources/0ad.desktop build/resources/0ad.png ${CRAFT_PART_INSTALL}/
      sed -i -e "s#Icon=0ad#Icon=/0ad.png#" ${CRAFT_PART_INSTALL}/0ad.desktop
  0ad-unix-data:
    plugin: dump
    source: https://jenkins.wildfiregames.com/job/0ad-bundles/lastSuccessfulBuild/artifact/0ad-0.28.0dev-unix-data.tar.xz
    source-checksum: sha1/226639a31dfcdef41cf022a38346e74f8aa96e1f
    organize:
      config: binaries/data/config
      mods: binaries/data/mods
      tools: binaries/data/tools
  0ad-launcher:
    plugin: dump
    source: .
    prime:
      - etc/fonts/
      - usr/bin/update-mime-database
      - usr/lib/
      - usr/share/glib-2.0/schemas
      - usr/share/fonts/
      - usr/share/mime/
      - usr/share/themes/
      - play0ad.launcher
    stage-packages:
      - libboost-filesystem1.83.0
      - libcurl3t64-gnutls
      - libenet7
      - libfmt9
      - libfreetype6
      - libglib2.0-0t64
      - libgloox18
      - libgtk-3-common
      - libminiupnpc17
      - libopenal1
      - libpng16-16t64
      - libsdl2-2.0-0
      - libsodium23
      - libvorbis0a
      - libvorbisenc2
      - libvorbisfile3
      - libwxbase3.2-1t64
      - libwxgtk-gl3.2-1t64
      - libwxgtk3.2-1t64
      - libxcursor1
      - locales-all
      - shared-mime-info
  gpu-2404:
    after: [0ad-launcher]
    source: https://github.com/canonical/gpu-snap.git
    plugin: dump
    override-prime: |
      craftctl default
      ${CRAFT_PART_SRC}/bin/gpu-2404-cleanup mesa-2404
    prime:
      - bin/gpu-2404-wrapper
