name: 0ad
version: 0.0.25-rc4-25842-alpha
summary: Real-time strategy game of ancient warfare
description: |
 0 A.D. (pronounced “zero-ey-dee”) is a free, open-source, historical
 Real Time Strategy (RTS) game currently under development by Wildfire Games,
 a global group of volunteer game developers.
 As the leader of an ancient civilization, you must gather the resources
 you need to raise a military force and dominate your enemies.
 .
 “0 A.D.” is a time period that never actually existed: In the usual calendar,
 one goes from 1 B.C. to 1 A.D. and skips zero. This reflects the historical
 fiction in the game: Who would have won if all the factions were pitted
 against each other when each of them was at its prime?
 .
 We intend to portray some of the major civilizations over the millennium of
 500 B.C. to 500 A.D. (Hence the midpoint, zero.) That is an ambitious prospect,
 so in the first edition of 0 A.D. we focus on the last five centuries B.C.
 Perhaps in future expansion packs, more civilizations will be added,
 along with additional gameplay features.
 .
 We put a strong emphasis on historical accuracy while developing 0 A.D.
 We plan all our units and all our buildings based on reconstructions of how
 the units and the buildings might have looked like in the ancient world.
 We even name them in the original languages, such as Greek and Latin.
 But it’s worth remembering that any game should be fun to play, so,
 in many cases, we preferred playability over historical accuracy.
confinement: strict
base: core18

apps:
  0ad:
    command: play0ad.launcher
    desktop: 0ad.desktop
    common-id: com.play0ad.zeroad
    plugs:
      - audio-playback
      - home
      - network
      - network-bind
      - opengl
      - process-control
      - pulseaudio # remove once snapd 2.41 is available everywhere
      - removable-media
      - screen-inhibit-control
      - x11
  atlas:
    command: play0ad.launcher -editor
    plugs:
      - audio-playback
      - home
      - opengl
      - process-control
      - pulseaudio # remove once snapd 2.41 is available everywhere
      - removable-media
      - x11

layout:
  /usr/share/libdrm:
    bind: $SNAP/usr/share/libdrm

parts:
  0ad-patches:
    plugin: nil
    source: patches
    override-build: |
      mkdir -p $SNAPCRAFT_PART_INSTALL/patches
      cp *.patch $SNAPCRAFT_PART_INSTALL/patches/
    override-prime: ""
  0ad-unix-build:
    after: [ 0ad-patches ]
    plugin: nil
    source: https://releases.wildfiregames.com/rc/0ad-0.0.25-rc4-25842-alpha-unix-build.tar.xz
    source-checksum: sha1/8b8db723b7597ec1ff92fa5f888e9d1eec6ddcb9
    build-packages:
      - cargo
      - cmake
      - libboost-dev
      - libboost-filesystem-dev
      - libcurl4-gnutls-dev
      - libenet-dev
      - libfmt-dev
      - libgloox-dev
      - libicu-dev
      - libminiupnpc-dev
      - libnspr4-dev
      - libogg-dev
      - libopenal-dev
      - libpng-dev
      - libsdl2-dev
      - libsodium-dev
      - libvorbis-dev
      - libwxgtk3.0-dev
      - libxcursor-dev
      - libxml2-dev
      - patch
      - pkg-config
      - python
      - rustc
      - zlib1g-dev
    override-build: |
      patch -d . -p1 < $SNAPCRAFT_STAGE/patches/allow-build-with-root.patch
      build/workspaces/update-workspaces.sh -j$SNAPCRAFT_PARALLEL_BUILD_COUNT
      make -j$SNAPCRAFT_PARALLEL_BUILD_COUNT config=release -C build/workspaces/gcc
      P=binaries/system
      mkdir -p $SNAPCRAFT_PART_INSTALL/$P
      cp $P/libnvcore.so $P/libnvimage.so $P/libnvmath.so $P/libnvtt.so $SNAPCRAFT_PART_INSTALL/$P/
      cp $P/pyrogenesis $P/ActorEditor $P/libAtlasUI.so $P/libCollada.so $P/libmozjs*-ps-release.so $P/readme.txt $SNAPCRAFT_PART_INSTALL/$P/
      P=binaries/data/l10n
      mkdir -p $SNAPCRAFT_PART_INSTALL/$P
      cp $P/*.po $SNAPCRAFT_PART_INSTALL/$P/
      cp build/resources/0ad.desktop $SNAPCRAFT_PART_INSTALL/
      sed -i -e "s#Icon=0ad#Icon=/icon.png#" $SNAPCRAFT_PART_INSTALL/0ad.desktop
  0ad-unix-data:
    plugin: dump
    source: https://releases.wildfiregames.com/rc/0ad-0.0.25-rc4-25842-alpha-unix-data.tar.xz
    source-checksum: sha1/923ee2d273396333cd4d2083a01ff00b6fb48475
    organize:
      config: binaries/data/config
      mods: binaries/data/mods
      tools: binaries/data/tools
  0ad-launcher:
    plugin: dump
    source: .
    prime:
      - etc/fonts/
      - lib/
      - usr/lib/
      - usr/share/fonts/
      - usr/share/libdrm/
      - usr/share/themes/
      - usr/share/X11/
      - play0ad.launcher
      - icon.png
    stage-packages:
      - libboost-filesystem1.65.1
      - libboost-system1.65.1
      - libcurl3-gnutls
      - libdrm-common
      - libenet7
      - libgl1-mesa-glx
      - libgloox15
      - libicu60
      - libminiupnpc10
      - libnspr4
      - libopenal1
      - libpng16-16
      - libsdl2-2.0-0
      - libsodium23
      - libvorbisfile3
      - libwxbase3.0-0v5
      - libwxgtk3.0-0v5
      - libx11-6
      - libxcursor1
      - libxml2
      - locales-all
