name: Update to the latest nightly build

on:
  schedule:
    # Run daily at 08:00 UTC
    - cron: '0 8 * * *'
  # Allow running manually, for testing purposes
  workflow_dispatch:

concurrency: ${{ github.workflow }}

jobs:
  nightly-build:
    runs-on: ubuntu-latest
    steps:
      - name: Install dependencies
        run: |
          sudo apt update
          sudo apt install -y coreutils curl diffutils grep patch
          sudo snap install yq
      - uses: actions/checkout@v6
        with:
          ref: edge
          persist-credentials: false
      - name: Update to the latest nightly build
        run: ./check-and-update-nightly-build.sh
      - name: Commit updated snapcraft.yaml
        uses: actions-js/push@master
        with:
          github_token: ${{ secrets.COMMIT_TOKEN }}
          branch: edge
          message: "Update to the latest nightly build"

